---
ID: "7d94ee2b-a8ef-4134-9ae0-9b892a1bad19"
Parent: "00858ec4-7324-4838-b404-5677f6a92f5d"
Template: "00858ec4-7324-4838-b404-5677f6a92f5d"
Path: /sitecore/templates/Feature/Tvs Headless/Navigation/_NavigationItem/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190307T181004Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
          sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "add4a4bd-5470-41c9-b176-f999341ec318"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240302T172947Z
